#pragma once
#define READY "Ready."
#define CONNECTION_FAILED "Cannnot connect to server!"
#define WAITING_FOR_OPPONENT "Waiting for opponent..."
#define WAITING_OPPONENT_MOVE "Waiting opponent to move first..."
#define GAME_STARTED "Game started. Please place first."
#define OPPONENT_ACTION "Opponent last move: "
#define WINNER "Winner is:"
#define USER_1 "Black"
#define USER_2 "White"
#define RESETTING_GAME "Game reseted. Start a new game!"