#pragma once
#define READY "Ready."
#define CONNECTION_FAILED "Cannnot connect to server!"
#define WAITING_FOR_OPPONENT "Waiting for opponent..."
#define WAITING_OPPONENT_MOVE "Waiting opponent to move first..."
#define GAME_STARTED "Game started. Please place first."
#define OPPONENT_ACTION "Opponent last move: "
#define WINNER "Winner is:"
#define USER_1 "Black"
#define USER_2 "White"
#define RESETTING_GAME "Game reseted. Start a new game!"
#define QUICK_MATCH "Quick Match"
#define SERVER_STATUS "Server Status: OK"
#define RANKED_SOLO "Ranked Solo"
#define AI_CHALLENGE "AI Challenge"
#define CN_SERVER "Shanghai (v27 Stable)"
#define CA_SERVER "Canada (v18 Not avalible)"
#define LOCALHOST "Localhost"
#define SERVER "Server:"
#define NO_MULTIPLAYING "Multiplaying is forbidden!"
#define COMING_SOON "Coming soon..."
#define STATUS "Status: "
#define RANKING_UI "Ranking"