#pragma once
#define READY "就绪"
#define CONNECTION_FAILED "无法连接到服务器！"
#define WAITING_FOR_OPPONENT "正在匹配对手..."
#define WAITING_OPPONENT_MOVE "等待对手先执子..."
#define GAME_STARTED "游戏开始。你是黑子，请黑子先行。"
#define OPPONENT_ACTION "上一步: "
#define WINNER "胜利者:"
#define USER_1 "黑子"
#define USER_2 "白子"
#define RESETTING_GAME "游戏复位成功！请开始一局新的游戏！"
#define QUICK_MATCH "匹配模式"
#define SERVER_STATUS "服务器连接正常。"
#define RANKED_SOLO "排位模式"
#define AI_CHALLENGE "AI挑战"
#define CN_SERVER "上海一区 (v27 正常)"
#define CA_SERVER "海外一区 (v18 维护)"
#define LOCALHOST "本地调试"
#define SERVER "服务器:"
#define NO_MULTIPLAYING "禁止多开游戏!"
#define COMING_SOON "敬请期待..."
#define STATUS "状态: "
#define RANKING_UI "排行榜"